# Generated by Django 5.0.4 on 2024-04-30 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orderproduct_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='message',
            new_name='details',
        ),
    ]
