# Generated by Django 5.0.4 on 2024-05-09 09:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_date_order_createddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='hour',
            field=models.PositiveIntegerField(default=12),
            preserve_default=False,
        ),
    ]
